// Package settings Code generated .* DO NOT EDIT\.$
// This file was generated by robots at
// 2023-10-20 23:49:17.400013302 +0800 CST m=+0.000300773
package settings

var ServerHost = "127.0.0.1"
var ServerPort = "9980"
var AllOutputByte  = []byte("\xff")
var AllOutputStr  = `aaa`